Add an ansible-runner test case
This adds a test case for the ansible-runner script which:

* Creates an upstream git repo containing a playbook and a requirements.txt
* Clones the upstream, runs the ansible-runner
* Asserts playbook is run and that requirements have been installed
* Updates the upstream playbook, runs ansible-runner
* Asserts updates have been pulled down and the playbook has been run
* Adds a new requirement, runs the ansible-runner
* Asserts the new requirement has been installed into expected venv

This required removing a bunch of hard-coded paths from the ansible-runner
script.

Also, organized the tests/ directory a bit and moved non-script things into
a files/ subdir.

Resolves-Issue: BonnyCI/projman#163
Signed-off-by: Adam Gandelman <adamg@ubuntu.com>

diff --git a/roles/ansible-runner/files/usr/local/bin/ansible-runner b/roles/ansible-runner/files/usr/local/bin/ansible-runner
--- a/roles/ansible-runner/files/usr/local/bin/ansible-runner
+++ b/roles/ansible-runner/files/usr/local/bin/ansible-runner
@@ -3,7 +3,20 @@
 set -eu
 
 env=$1
-. /etc/default/$env
+envs_root=${ANSIBLE_RUNNER_ENV_ROOT:-/opt/source}
+ansible_venv=${ANSIBLE_RUNNER_VENV:-/opt/ansible}
+log_dir=${ANSIBLE_RUNNER_LOG_DIR:-/var/www/html/cron-logs/$env/}
+ssh_user=${ANSIBLE_SSH_USER:-""}
+
+
+if [ -f /etc/default/$env ]; then
+  . /etc/default/$env
+fi
+
+if ! ([ -n "$ANSIBLE_PLAYBOOK" ] && [ -n "$ANSIBLE_INVENTORY" ]); then
+  echo "Missing all required environment variables: ANSIBLE_PLAYBOOK, ANSIBLE_INVENTORY"
+  exit 1
+fi
 
 if [ -f /etc/disable-ansible-runner-$env ]; then
     echo "Environment $env is disabled by file."
@@ -18,28 +31,31 @@ fi
 shift
 
 set +u
-. /opt/ansible/bin/activate
+. $ansible_venv/bin/activate
 set -u
 
 playbook=$(basename $ANSIBLE_PLAYBOOK)
 timestamp=$(date +%Y%m%d%H%M%S)
-logfile="/var/www/html/cron-logs/$env/ansible_${playbook}_current.log"
-dst_logfile="/var/www/html/cron-logs/$env/ansible_${playbook}_${timestamp}.log"
+logfile="$log_dir/ansible_${playbook}_current.log"
+dst_logfile="$log_dir/ansible_${playbook}_${timestamp}.log"
 
-trap "cp $logfile $dst_logfile; rm -f /var/www/html/cron-logs/$env/ansible_${playbook}_latest.log; ln -s $dst_logfile /var/www/html/cron-logs/$env/ansible_${playbook}_latest.log" EXIT
+trap "cp $logfile $dst_logfile; rm -f $log_dir/ansible_${playbook}_latest.log; ln -s $dst_logfile $log_dir/ansible_${playbook}_latest.log; deactivate" EXIT
 
 date 2>&1 | tee $logfile
 basename "$logfile" 2>&1 | tee -a $logfile
-cd /opt/source/$env
+cd $envs_root/$env
 git pull 2>&1 | tee -a $logfile
-sudo /opt/ansible/bin/pip install -U -r requirements.txt 2>&1 | tee -a $logfile
+
+if [ -f requirements.txt ]; then
+  sudo $ansible_venv/bin/pip install -U -r requirements.txt 2>&1 | tee -a $logfile
+fi
 
 args="$@"
-if [ -n "$ANSIBLE_SSH_USER" ]; then
-    args="$args -e ansible_ssh_user=$ANSIBLE_SSH_USER"
+if [ -n "$ssh_user" ]; then
+    args="$args -e ansible_ssh_user=$ssh_user"
 fi
-ansible-playbook -vv -i $ANSIBLE_INVENTORY $args $ANSIBLE_PLAYBOOK 2>&1 | tee -a $logfile
+$ansible_venv/bin/ansible-playbook -vv -i $ANSIBLE_INVENTORY $args $ANSIBLE_PLAYBOOK 2>&1 | tee -a $logfile
 date 2>&1 | tee -a $logfile
 
 # Remove > 10 days old
-find /var/www/html/cron-logs/$env -type f -name '*.log' -mtime 10 -exec rm -f {} \;
+find $log_dir -type f -name '*.log' -mtime 10 -exec rm -f {} \;
